employee_survey/employee_survey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from employee_survey_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^employee_survey_app/', include('employee_survey_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

admin.site.site_header = "Survey Admin"
admin.site.site_title = "Survey Admin Portal"
admin.site.index_title = "Welcome to Employee Survey Portal"

employee_survey/employee_survey_app/urls.py
# pylint: disable=invalid-name
# pylint: disable=missing-docstring
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'employee_survey_app'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'user_survey_assignment/$', views.user_survey_assignment, name='user_survey_assignment'),
    url(r'survey_report/$', views.survey_report, name='survey_report'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^my_surveys/$', views.EmployeeSurveys.as_view(), name='my_surveys'),
    # url(r'^my_surveys/(?P<id>[-\w]+)/$', views.survey_detail, name='detail'),
    url(r'^my_surveys/(?P<id>[-\w]+)/$', views.survey_detail, name='my_surveys_detail'),
    url(r'^confirm/(?P<uuid>\w+)/$', views.confirm, name='confirmation')
]

employee_survey/employee_survey_app/models.py
# pylint: disable=invalid-name
# pylint: disable=broad-except
# pylint: disable=missing-docstring
# pylint: disable=no-member
# pylint: disable=too-few-public-methods
# pylint: disable=too-many-branches
# pylint: disable=too-many-statements
import datetime
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Organisation(models.Model):
    name = models.CharField(max_length=256)
    is_archived = models.BooleanField(null=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, blank=True, null=True,
                                     related_name='organisations')


class Category(models.Model):
    name = models.CharField(max_length=400)
    # survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Question(models.Model):
    TEXT = 'text'
    RADIO = 'radio'
    SELECT = 'select'
    SELECT_MULTIPLE = 'select-multiple'
    INTEGER = 'integer'

    QUESTION_TYPES = (
        (TEXT, 'text'),
        (RADIO, 'radio'),
        (SELECT, 'select'),
        (SELECT_MULTIPLE, 'Select Multiple'),
        (INTEGER, 'integer'),
    )

    text = models.TextField()
    required = models.BooleanField()
    # category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    # survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_type = models.CharField(max_length=200, choices=QUESTION_TYPES, default=TEXT)
    # the choices field is only used if the question type
    choices = models.TextField(blank=True, null=True, help_text='if the question type is "radio," "select,'
                                                                '" or "select multiple" '
                                                                'provide a comma-separated list of options'
                                                                ' for this question .')

    def save(self, *args, **kwargs):
        if (self.question_type == Question.RADIO or self.question_type == Question.SELECT or self.question_type ==
                Question.SELECT_MULTIPLE):
            validate_list(self.choices)
        super(Question, self).save(*args, **kwargs)

    def get_choices(self):
        """ parse the choices field and return a tuple formatted appropriately
        for the 'choices' argument of a form widget."""
        choices = self.choices.split(',')
        choices_list = []
        for c in choices:
            c = c.strip()
            choices_list.append((c, c))
        choices_tuple = tuple(choices_list)
        return choices_tuple

    def __unicode__(self):
        return self.text

    def __str__(self):
        return self.text


class Survey(models.Model):
    name = models.CharField(max_length=400)
    description = models.TextField()
    user = models.ManyToManyField(User, through='SurveyUser')
    questions = models.ManyToManyField(Question)

    def __unicode__(self):
            return self.name

    def __str__(self):
        return self.name

    # def questions(self):
    #         if self.pk:
    #             return Question.objects.filter(survey=self.pk)
    #         else:
    #             return None


# class SurveyQuestions(models.Model):
#     survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)


class SurveyUser(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField()

    def __str__(self):
        return self.survey.name


'''
takes a text value and verifies that there is at least one comma 
'''


def validate_list(value):
    values = value.split(',')
    if len(values) < 2:
        raise ValidationError("The selected field requires "
                              "an associated list of choices. Choices must contain more than one item.")


class Response(models.Model):
    # a response object is just a collection of questions and answers with a
    # unique interview uuid
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.TextField('Any additional Comments', blank=True, null=True)
    interview_uuid = models.CharField("Interview unique identifier", max_length=36)
    is_finished = models.BooleanField(default=False, blank=True, null=True)
    survey_user_id = models.ForeignKey(SurveyUser, on_delete=models.CASCADE, null=True)

    def __unicode__(self):
        return "response %s" % self.interview_uuid


class AnswerBase(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    response = models.ForeignKey(Response, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

# these type-specific answer models use a text field to allow for flexible
# field sizes depending on the actual question this answer corresponds to. any
# "required" attribute will be enforced by the form.


class AnswerText(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerRadio(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerSelect(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerSelectMultiple(AnswerBase):
    body = models.TextField(blank=True, null=True)


class AnswerInteger(AnswerBase):
    body = models.IntegerField(blank=True, null=True)

employee_survey/employee_survey_app/views.py
# pylint: disable=invalid-name
# pylint: disable=broad-except
# pylint: disable=missing-docstring
# pylint: disable=no-member
# pylint: disable=too-few-public-methods
# pylint: disable=too-many-branches
# pylint: disable=too-many-statements
import logging
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth import get_user_model
from employee_survey_app import models
from employee_survey_app import EmailModel
from .forms import UserForm, UserSurveyAssignmentForm, ResponseForm
from .models import Survey, Category, Response, SurveyUser, Organisation

User = get_user_model()
# Get an instance of a logger
logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'employee_survey_app/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def survey_report(request):
    if request.user.is_staff:
        if request.user.is_superuser:
            result = SurveyUser.objects.all()
            response = list()
            for i in result:
                obj = dict()
                obj['id'] = i.id
                obj['survey'] = i.survey
                obj['user'] = i.user
                obj['start_date'] = i.start_date
                obj['end_date'] = i.end_date
                obj['is_past_end_date'] = date.today() > i.end_date
                is_response = Response.objects.filter(survey_user_id=i.id)
                if is_response:
                    obj['response'] = is_response[0]
                    response.append(obj)
                else:
                    response.append(obj)
        elif request.user.groups.filter(name='SuperAdmin').exists():
            # response = Response.objects.all()
            result = SurveyUser.objects.all()
            response = list()
            for i in result:
                obj = dict()
                obj['id'] = i.id
                obj['survey'] = i.survey
                obj['user'] = i.user
                obj['start_date'] = i.start_date
                obj['end_date'] = i.end_date
                obj['is_past_end_date'] = date.today() > i.end_date
                is_response = Response.objects.filter(survey_user_id=i.id)
                if is_response:
                    obj['response'] = is_response[0]
                    response.append(obj)
                else:
                    response.append(obj)
        elif request.user.groups.filter(name='OrganisationAdmin').exists():
            # response = Response.objects.filter(user__organisation_id=request.user.organisation_id)
            result = SurveyUser.objects.filter(user__organisation_id=request.user.organisation_id)
            response = list()
            for i in result:
                obj = dict()
                obj['id'] = i.id
                obj['survey'] = i.survey
                obj['user'] = i.user
                obj['start_date'] = i.start_date
                obj['end_date'] = i.end_date
                obj['is_past_end_date'] = date.today() > i.end_date
                is_response = Response.objects.filter(survey_user_id=i.id)
                if is_response:
                    obj['response'] = is_response[0]
                    response.append(obj)
                else:
                    response.append(obj)
        else:
            # response = Response.objects.filter(user_id=request.user.id)
            result = SurveyUser.objects.filter(user_id=request.user.id)
            response = list()
            for i in result:
                obj = dict()
                obj['id'] = i.id
                obj['survey'] = i.survey
                obj['user'] = i.user
                obj['start_date'] = i.start_date
                obj['end_date'] = i.end_date
                obj['is_past_end_date'] = date.today() > i.end_date
                is_response = Response.objects.filter(survey_user_id=i.id)
                if is_response:
                    obj['response'] = is_response[0]
                    response.append(obj)
                else:
                    response.append(obj)
    else:
        # response = Response.objects.filter(user_id=request.user.id)
        result = SurveyUser.objects.filter(user_id=request.user.id)
        response = list()
        for i in result:
            obj = dict()
            obj['id'] = i.id
            obj['survey'] = i.survey
            obj['user'] = i.user
            obj['start_date'] = i.start_date
            obj['end_date'] = i.end_date
            obj['is_past_end_date'] = date.today() > i.end_date
            is_response = Response.objects.filter(survey_user_id=i.id)
            if is_response:
                obj['response'] = is_response[0]
                response.append(obj)
            else:
                response.append(obj)
    return render(request, 'employee_survey_app/survey_report.html', {'response': response})


def register(request):
    registered = False
    user = request.user
    if request.method == 'POST':
        user_form = UserForm(logged_in_user=user, data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            logger.exception("Exception in user_form", user_form.errors)
    else:
        user_form = UserForm(logged_in_user=user)
        if request.user.is_staff and not request.user.is_superuser:
            if request.user.groups.filter(name='OrganisationAdmin').exists():
                user_form = UserForm(logged_in_user=user, initial={'organisation': request.user.organisation_id})

    return render(request, 'employee_survey_app/registration.html',
                  {'user_form': user_form, 'logged_in_user': user, 'registered': registered})


def user_survey_assignment(request):
    if request.method == 'POST':
        user_survey_form = UserSurveyAssignmentForm(data=request.POST)
        if user_survey_form.is_valid():
            users_survey = user_survey_form.save()
            users_survey.save()
            data = request.POST.copy()
            try:
                user_id = data.get('user')
                survey_id = data.get('survey')
                user = User.objects.get(id=user_id)
                survey = Survey.objects.get(id=survey_id)
                subject = "Assignment of Survey"
                sms_text = "You have assigned new survey", survey.name
                email_to = [user.email]
                EmailModel.send_mail_fun(subject, sms_text, email_to)
            except Exception as e:
                logger.exception("Exception in Assign users to survey", e)

            return HttpResponse("Assignment Done Successfully")
    else:
        user_survey_form = UserSurveyAssignmentForm()
    return render(request, 'employee_survey_app/UsersSurveyAssignment.html',
                  {'user_survey_form': user_survey_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'employee_survey_app/login.html', {})


def survey_detail(request, id):
    survey_user_id = id
    survey_user = SurveyUser.objects.get(id=survey_user_id)
    is_past_end_date = date.today() >= survey_user.end_date
    survey = Survey.objects.get(id=survey_user.survey_id)
    # category_items = Category.objects.filter(survey=survey)
    # categories = [c.name for c in category_items]
    user = request.user
    is_finished = False
    comments = ""
    if request.method == 'POST':
        if 'save_btn' in request.POST:
            is_finished = False
        elif 'finish_btn' in request.POST:
            is_finished = True

        try:
            user_response = Response.objects.get(survey=survey, user=user, survey_user_id=survey_user_id)
            response_id = user_response.id
        except Exception as e:
            response_id = 0
            logger.exception("Exception in survey_detail - response_id", e)

        if response_id:
            f = Response.objects.get(pk=response_id)
            form = ResponseForm(request.POST, request.FILES, instance=f, survey=survey,
                                user=user, is_finished=is_finished, user_response_id=response_id,
                                is_past_end_date=is_past_end_date, survey_user_id=survey_user_id)
        else:
            form = ResponseForm(request.POST, survey=survey, user=user,
                                is_finished=is_finished, is_past_end_date=is_past_end_date,
                                user_response_id=response_id, survey_user_id=survey_user_id)

        if form.is_valid():
            response = form.save()
            if is_finished:
                subject = "Complete Survey : ", survey.name
                sms_text = "Hello ", user.username, ", \n Thank you for completing survey ",\
                           survey.name, "."
                email_to = [user.email]
                EmailModel.send_mail_fun(subject, sms_text, email_to)

employee_survey/templates/employee_survey_app/UsersSurveyAssignment.html
{% extends "employee_survey_app/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h2>Welcome to the Employee Survey System !</h2>
    {% if user.is_superuser %}
        <h2>Assign Survey to Users</h2>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_survey_form.as_p }}
          <input type="submit" name="" value="Assign">
        </form>
    {% else %}
        <h2>You are not authorised person for assignment</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

employee_survey/templates/employee_survey_app/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href=" https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">

      <!-- Le styles -->
	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

	<![endif]-->

  </head>
  <body>
   <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
                  <li class="nav-item">
                      <a class="navbar-brand" href="{% url 'index' %}" >Employee Survey</a>
                  </li>
                  <li class="nav-item">
                      <a class="navbar-link" href="{% url 'admin:index' %}" >Admin</a>
                  </li>
                  <li class="nav-item">
                      <a class="navbar-link" href="{% url 'employee_survey_app:register' %}" >Register</a>
                  </li>
                  <li class="nav-item">
                      <a class="navbar-link" href="{% url 'employee_survey_app:survey_report' %}">Report</a>
                  </li>
                  {# Some logic on what to display for last item#}
                  {% if user.is_authenticated %}
                    <li class="nav-item" style="float: left;">
                        <i class="fa fa-user-circle-o"></i>
                        <a href="{% url 'logout' %}">
                          <i class="fa fa-user-circle-o"></i>
                          <label style="color:green;text-decoration: underline;">{{user.username}} </label> Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                        <a class="navbar-link" href="{% url 'employee_survey_app:user_login' %}">Login</a>
                    </li>
                  {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  <!-- Le javascript -->
	<link rel="stylesheet" href="{% static 'css/flick/jquery-ui-1.9.1.custom.css' %}" />
	<script src="{% static 'js/jquery-1.8.2.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
	<script src="{% static 'js/jquery-ui-1.9.1.custom.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
	<script>
		// use the jquery UI datepicker on all pages with the datepicker class:
		$(".datepicker").datepicker({ minDate: 0});
		  $('.readonly').find('input, textarea, select').attr('readonly', 'readonly');
		// $(".readonly").find('input, textarea, select').attr("disabled", true);
	</script>
  </body>
</html>

employee_survey/templates/employee_survey_app/confirm.html
{% extends 'employee_survey_app/base.html' %}

{% block body_block %}

Thanks for your feedback!

{% endblock %}

employee_survey/templates/employee_survey_app/employee_surveys.html
{% extends "employee_survey_app/base.html" %}
{% block body_block %}
<style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        th{
            color: black;
        }
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }

        tr:nth-child(even) {
          background-color: #dddddd;
        }
    </style>
<h2 style="color:#000080">Welcome to Employee Survey System!</h2>
{% if UsersSurveys %}
    <table>
        <tr>
            <th>Survey Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Action</th>
        </tr>
         {% for survey in UsersSurveys %}
            <tr>
                 <td>{{survey.survey.name}}</td>
                 <td>{{survey.start_date}}</td>
                 <td>{{survey.end_date}}</td>
                 <td>
                     {% if survey.is_past_start_date%}
                        {% if survey.is_past_end_date %}
                            <a href="{{survey.id}}" style="color:red;text-decoration:underline;">Expired..!</a>
                        {% elif survey.response %}
                            {% if survey.response.is_finished %}
                                <a href="{{survey.id}}" style="text-decoration:underline;"> Re-start </a>
                            {% else %}
                                <a href="{{survey.id}}" style="text-decoration:underline;">Continue </a>
                            {% endif %}
                        {% else %}
                            <a href="{{survey.id}}" style="text-decoration:underline;">Start</a>
                        {% endif %}
                     {% else %}
                        <label style="color:green;"> Coming soon</label>
                     {% endif %}
                 </td>
            </tr>
         {% endfor %}
    </table>
{% else %}
      <p style="color:#ff0000">There are no surveys.</p>
{% endif %}
{% endblock %}

employee_survey/templates/employee_survey_app/index.html
{% extends "employee_survey_app/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h2>Welcome to the Employee Survey System !</h2>
    {% if user.is_authenticated %}
        <h4 style="color:blue">Hello {{ user.username }}</h4>
        <li><a href="{% url 'employee_survey_app:my_surveys' %}" style="color:#cc0052">Take Your Surveys</a></li>

    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

employee_survey/templates/employee_survey_app/login.html
{% extends 'employee_survey_app/base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-offset-3 col-md-3">
                <form method="post" action="{% url 'employee_survey_app:user_login' %}">
                    {% csrf_token %}
                    {# A more "HTML" way of creating the login form#}
                    <div class="form-login">
                <h4>Welcome to Login </h4>
                <input type="text" id="username" class="form-control input-sm chat-input" name="username"
                       placeholder="username" />
                </br>
                <input type="password" id="password" class="form-control input-sm chat-input"  name="password"
                       placeholder="password" />
                </br>
                <div class="wrapper">
                <span class="group-btn">
                    <input type="submit" class="btn btn-primary btn-md" name="" value="Login">
                </span>
                </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

employee_survey/templates/employee_survey_app/registration.html
{% extends "employee_survey_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h2 style="text-align:center">User Registration</h2>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
            <div class="form-group row">
              <label for="id_username" class="col-sm-2 col-form-label">Username</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="username"  placeholder="Username" maxlength="150" required="" id="id_username">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_password" class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" name="password" required="" id="id_password" placeholder="Password">
              </div>
            </div>
           <div class="form-group row">
              <label for="id_email" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                <input type="email"  class="form-control"  name="email" maxlength="254" id="id_email" placeholder="Email">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_organisation" class="col-sm-2 col-form-label">Organisation</label>
              <div class="col-sm-10">
                {{ user_form.organisation}}
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Sign in</button>
              </div>
            </div>
          </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

employee_survey/templates/employee_survey_app/survey.html
{% extends 'employee_survey_app/base.html' %}
{% load survey_extras %}

{% block body_block %}
<div class="container">
	{% if is_past_end_date %}
		<h2 style="color:red">welcome {{user}}, your survey is expired..!! </h2>
        <label><span class="asterix"> * </span>You can only see your previous feedback</label>
	{% else %}
		{% if user_response_id %}
			<h2 style="color:#000080">welcome {{user}}, now re-start your feedback ...</h2>
		{% else %}
			<h2 style="color:#000080">welcome {{user}}, now start your feedback ...</h2>
		{% endif %}
	{% endif %}
	<h4>About {{survey.name|title}} </h4>
	<div class="survey-description">
		{{survey.description|safe}}
	</div>

	<div class="card" style="disabled:{{is_past_end_date}}">
		<div class="card-header"></div>
		<div class="card-body">
			<form name="frm-survey" id="frm-example"  action="/employee_survey_app/my_surveys/{{survey_user_id}}/" method="POST">{% csrf_token %}
				<div class="category-container">
					<div  style="visibility:hidden">
							{{ response_form.user }}
					</div>
					<table>
						<tr class="field-wrapper">
							<td>
								{{ response_form.comments.label_tag }}
							</td>
							<td>
								{{ response_form.comments.errors }}
								{{ response_form.comments.help_text}}
								{{ response_form.comments }}
							</td>
						</tr>
					</table>
				</div>
				<div class="panel panel-default survey_panel">
					<div class="panel-body">
						<table id="example" class="table" style="width:100%"  data-page-length='5'>
						<thead>
							<tr>
								<th>Sr. No.</th>
								<th>Question</th>
								<th>Answer</th>
							</tr>
						</thead>
						<tbody>
							{% for field in response_form %}
								{% if field.field.widget.attrs.category == 'test_cat' %}
									<tr class="q-item" value="{% counter %}">
										<td>{% counter %}</td>
										{% if field.field.required %}
											<td>
												{{ field.errors }}
												<span class="asterix"> * </span><label class="label-inline">{{ field.label }}</label>
												<span class="form-help-text">{{ field.help_text}}</span>
											</td>
										{% else %}
											<td>
												{{ field.errors }}
												<label class="label-inline">{{ field.label }}</label>
												<span class="form-help-text">{{ field.help_text}}</span>
											</td>
										{% endif %}
										<td>
											{{ field }}
										</td>
									</tr>
								{% endif %}
							{% endfor %}
						</tbody>
						<tfoot>
						</tfoot>
					</table>
					</div>
				</div>
				<div class="submit-button">
					{% if is_past_end_date %}
						<input type="submit" class="btn btn-primary btn-md" name="save_btn"
							   value="Save" disabled>
						<input type="submit" class="btn btn-success btn-md" name="finish_btn"
							   value="Finish" disabled>
					{% else %}
						<input type="submit" class="btn btn-primary btn-md" name="save_btn"
							   value="Save">
						<input type="submit" class="btn btn-success btn-md" name="finish_btn"
							   value="Finish">
					{% endif %}

				</div>
			</form>
		</div>
	</div>

	{% endblock %}

	{% block extra_js %}
		<script src="/media/js/jquery.collapsible.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//collapsible management
				$('.collapsible').collapsible({defaultOpen: 'response_metadata'});
			});
		</script>
	{% endblock %}
</div>